import '../styles/globals.css'
import Header from './components/Header'
import Sidebar from './components/Sidebar'

export const metadata = {
  title: 'ShopGenie || Make a wish!',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">  
      <body>
        {/* to make the header dynamically available in all pages */}
        <Header/>
        <div className='w-full flex pt-3 pl-8'>
          <Sidebar/>
        <div className='w-full -ml-2 md:ml-5  h-[80vh] overflow-y-auto'>{children}</div>
        </div>
      </body>
    </html>
  )
}
